# Generated by Django 5.2.3 on 2025-06-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='animal',
            name='arrival_date',
            field=models.DateField(default='2025-06-10'),
            preserve_default=False,
        ),
    ]
