# Generated by Django 5.2.3 on 2025-07-04 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='animal',
            name='arrival_date',
            field=models.DateField(default=datetime.date(2025, 7, 4)),
        ),
        migrations.AlterField(
            model_name='animal_keeper',
            name='hire_date',
            field=models.DateField(default=datetime.date(2025, 7, 4)),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='checkup_date',
            field=models.DateField(default=datetime.date(2025, 7, 4)),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='follow_up_date',
            field=models.DateField(default=datetime.date(2025, 7, 4)),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='follow_up_notes',
            field=models.DateField(default=datetime.date(2025, 7, 4)),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='next_checkup',
            field=models.DateField(default=datetime.date(2025, 7, 4)),
        ),
        migrations.AlterField(
            model_name='supply',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2025, 7, 4)),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='hire_date',
            field=models.DateField(default=datetime.date(2025, 7, 4)),
        ),
    ]
