# Generated by Django 5.2.4 on 2025-07-04 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_alter_animal_options_alter_animal_arrival_date'),
        ('zoo', '0002_alter_animal_options_alter_animal_arrival_date_and_more'),
    ]

    operations = [
    ]
