# Generated by Django 5.2.4 on 2025-07-05 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_merge_20250704_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_keeper',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='supplier',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='arrival_date',
            field=models.DateField(default=datetime.date(2025, 7, 5)),
        ),
        migrations.AlterField(
            model_name='animal_keeper',
            name='hire_date',
            field=models.DateField(default=datetime.date(2025, 7, 5)),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='checkup_date',
            field=models.DateField(default=datetime.date(2025, 7, 5)),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='follow_up_date',
            field=models.DateField(default=datetime.date(2025, 7, 5)),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='follow_up_notes',
            field=models.DateField(default=datetime.date(2025, 7, 5)),
        ),
        migrations.AlterField(
            model_name='healthcheck',
            name='next_checkup',
            field=models.DateField(default=datetime.date(2025, 7, 5)),
        ),
        migrations.AlterField(
            model_name='supply',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2025, 7, 5)),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='hire_date',
            field=models.DateField(default=datetime.date(2025, 7, 5)),
        ),
    ]
